development: &default
  adapter: postgresql
  encoding: unicode
  database: service_development
  pool: 10
  host: <%= ENV.fetch('PGHOST', '127.0.0.1') %>
  port: <%= ENV.fetch('PGPORT', '5432') %>
  username: <%= ENV.fetch('PGUSER', '') %>
  password: <%= ENV.fetch('PGPASSWORD', '') %>

test:
  <<: *default
  database: service_test

production:
  <<: *default
  database: service_production
